### ISSUE TITLE
Fix pdf wrapping issues

### ISSUE THREAD

**Issue by knoll3** [sarcophagus-org/sarcophagus-v2-app#291]
The pdf generated from the "Set Recipient" step has wrapping issues. The public key overflows off the page. Just a note, if you decide to wrap the public key, be sure there is no hyphen. 

![Image](https://user-images.githubusercontent.com/34484576/206799200-7191d8eb-99a9-4128-926d-37933614d8e6.png)

Documented on Notion
https://www.notion.so/sarcopahgus/Sarcophagus-Embalmer-V2-Issues-and-Feedback-516b8ddcf4f548de8d6bfc43ccd7918a#0b9c9ae5f845406cb78558801813aa68

**Comment by DarksightKellar** [comment]
There's two ways so far that I've found to solve this issue.

1. Add a `break` flag to the `Text` element rendering the key. This causes the text to wrap but with a hyphen. The task indicates that we gotta make sure there's no hyphen. But there's currently no way to remove it (see https://github.com/diegomura/react-pdf/issues/1416). 
However, copying this text, whether by triple-clicking or click-dragging, does _not_ copy the hyphen.
**[UPDATE: abandoned this solution because it suddenly stopped working]**

2. Manually split the string into two halves and render each on separate `Text` tags. This ensures there's no hyphen, but breaks triple-click to select and copy. User will have to click-drag to select and copy. A minor inconvenience.
